name: Called Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        
      - name: Print Variables
        run: |
          echo "Variable 1:"
          echo "Variable 2:"
