name: Called Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Variables
        run: |
          echo "Variable 1: ${{ env.VARIABLE1 }}"
          echo "Variable 2: ${{ env.VARIABLE2 }}"
