name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Determine new version
        id: new_version
        run: |
          commit_message=$(git log --format=%s -n 1)
          
          if echo "$commit_message" | grep -qE '^feat:'; then
            current_version=$(node -p "require('./package.json').version")
            new_version=$(npm --no-git-tag-version version minor)
            echo "::set-output name=version::$new_version"
            echo "::set-output name=current_version::$current_version"
          elif echo "$commit_message" | grep -qE '^fix:'; then
            current_version=$(node -p "require('./package.json').version")
            new_version=$(npm --no-git-tag-version version patch)
            echo "::set-output name=version::$new_version"
            echo "::set-output name=current_version::$current_version"
          else
            echo "No version change needed."
          fi
      
      - name: Use the new version
        run: |
          new_version=${{ steps.new_version.outputs.version }}
          current_version=${{ steps.new_version.outputs.current_version }}
          
          echo "New version: $new_version"
          echo "Current version: $current_version"
          # Use the new version for further actions or steps

