name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      #- name: Install dependencies
      #  run: npm ci
      
      - name: Determine new version
        id: new_version
        run: |
          commit_message=$(git log --format=%s -n 1)
          
          if echo "$commit_message" | grep -qE '^feat:'; then
            npm version minor --no-git-tag-version
          elif echo "$commit_message" | grep -qE '^fix:'; then
            npm version patch --no-git-tag-version
          else
            npm version prerelease --no-git-tag-version --preid=rc
          fi
      
      - name: Set outputs
        id: outputs
        run: |
          echo "::set-output name=version::$(node -p "require('./package.json').version")"
      
      - name: Use the new version
        run: |
          echo "New version: ${{ steps.outputs.outputs.version }}"
          # Use the new version for further actions or steps
