name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set Git user identity
        run: |
          git config --global user.email "raman.sauchuk@devstream.by"
          git config --global user.name "rsadevops"
      
      - name: Determine new version
        id: new_version
        run: |
          commit_message=$(git log --format=%s -n 1)
          
          if echo "$commit_message" | grep -qE '^feat:'; then
            current_version=$(node -p "require('./package.json').version")
            new_version=$(npm --no-git-tag-version version minor --allow-same-version)
            echo "version=$new_version" >> $GITHUB_OUTPUT
            echo "current_version=$current_version" >> $GITHUB_OUTPUT
          elif echo "$commit_message" | grep -qE '^fix:'; then
            current_version=$(node -p "require('./package.json').version")
            new_version=$(npm --no-git-tag-version version patch --allow-same-version)
            echo "version=$new_version" >> $GITHUB_OUTPUT
            echo "current_version=$current_version" >> $GITHUB_OUTPUT
          else
            echo "No version change needed."
          fi
      
      - name: Update package.json
        if: steps.new_version.outputs.version != ''
        id: update
        run: |
          new_version=${{ steps.new_version.outputs.version }}
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          npm --no-git-tag-version version $new_version --allow-same-version
          cat package.json
          git add package.json
          git commit -m "Bump version to $new_version"
      
      - name: Use the new version
        run: |
          new_version=${{ steps.update.outputs.new_version }}
          current_version=${{ steps.new_version.outputs.current_version }}
          
          echo "New version: $new_version"
          echo "Current version: $current_version"
          # Use the new version for further actions or steps
