name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Semantic versioning
        id: semantic_versioning
        uses: techulus/semantic-git-version@v1
        with:
          tag_prefix: 'v'
          release_branches: 'main'
          minor_bump_regex: '^feat:'
          patch_bump_regex: '^fix:'

      - name: Use semantic version
        run: |
          echo "Semantic version: ${{ steps.semantic_versioning.outputs.version }}"
