name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set Git user identity
        run: |
          git config --global user.email "raman.sauchuk@devstream.by"
          git config --global user.name "rsadevops"
      
      - name: Determine new version
        id: new_version
        run: |
          chmod +x ./scripts/determine_version.sh 
          bash ./scripts/determine_version.sh
      
      - name: Update package.json
        if: steps.new_version.outputs.version != ''
        id: tag
        run: |
          chmod +x ./scripts/Update_package.sh
          bash ./scripts/Update_package.sh ${{ steps.new_version.outputs.version }}
      
      - name: Use the new version
        run: |
          new_version=${{ steps.tag.outputs.new_version }}
          current_version=${{ steps.new_version.outputs.current_version }}
          
          echo "New version: $new_version"
          echo "Current version: $current_version"
