name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set Git user identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      
      - name: Determine new version
        id: new_version
        run: |
          previous_version=$(node -p "require('./package.json').version")
          commit_message=$(git log --format=%s -n 1)
          
          if echo "$commit_message" | grep -qE '^feat:'; then
            new_version=$(npx semver --increment minor $previous_version)
            echo "::set-output name=version::$new_version"
            echo "::set-output name=previous_version::$previous_version"
          elif echo "$commit_message" | grep -qE '^fix:'; then
            new_version=$(npx semver --increment patch $previous_version)
            echo "::set-output name=version::$new_version"
            echo "::set-output name=previous_version::$previous_version"
          else
            echo "::set-output name=version::$previous_version"
            echo "::set-output name=previous_version::$previous_version"
            echo "No version change needed."
          fi
      
      - name: Update package.json
        if: steps.new_version.outputs.version != steps.new_version.outputs.previous_version
        run: |
          new_version=${{ steps.new_version.outputs.version }}
          echo "::set-output name=new_version::$new_version"
          npm --no-git-tag-version version $new_version --allow-same-version
          git add package.json
          git commit -m "Bump version to $new_version"
      
      - name: Use the new version
        run: |
          new_version=${{ steps.new_version.outputs.version }}
          previous_version=${{ steps.new_version.outputs.previous_version }}
          
          echo "New version: $new_version"
          echo "Previous version: $previous_version"
          # Use the new version for further actions or steps
