name: Semantic Version

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
            
      - name: Version autogeneration
        id: tag
        run: |
          chmod +x ./scripts/generate_version.sh
          bash ./scripts/generate_version.sh
            
      - name: Use the new version
        run: |
          new_version=${{ steps.tag.outputs.new_version }}
          
          echo "New version: $new_version"
